version: '3'

services:
  api-rest:
    build:
      dockerfile: ./api.dockerfile
      context: .
    image: julio/api-rest
    container_name: service-api
    ports:
      - "8080:3001"
    networks:
      - api-nextwork
    depends_on:
      - "mysqlsrv"
    volumes:
      - ./:/var/www

  mysqlsrv:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "escola"
      MYSQL_ROOT_PASSWORD: "curso@2021"
    ports:
      - "3308:3306"
    volumes:
      - /home/julio/courses_dev/MySql:/var/lib/mysql
    container_name: mysql-api
    networks:
      - api-nextwork

networks:
  api-nextwork:
    driver: bridge
